try {
  3/0
  assert_true(false); // should never get here
} catch (e) {
  assert_equal("Arithmetic error: divide by zero", e.what())
}

